export const OPS_INCIDENTS_COPY = {
  title: "Incident Console",
  subtitle: "Paste a Reference ID to see what happened.",
  lookupPlaceholder: "Reference ID (e.g. req_abcd1234)",
  lookupButton: "Lookup",
  emptyLookup: "No incident found for that reference.",
  recentTitle: "Recent incidents",
  recentEmpty: "No incidents in the selected window.",
  filters: {
    surfaceLabel: "Surface",
    timeLabel: "Time",
    surfaceAll: "All",
    time15m: "15m",
    time24h: "24h",
    time7d: "7d",
    time1h: "1h",
    codeLabel: "Code",
    flowLabel: "Flow",
    searchPlaceholder: "Search requestId, message, user",
    highImpact: "High impact only",
  },
  copySnippet: "Copy support snippet",
  openDossier: "Open user dossier",
  copiedToast: "Copied",
  groupEmpty: "Try narrowing time range or surface.",
  exportLimit: "Too many results to export. Narrow filters to export up to 500 groups.",
  relatedTitle: "Related events nearby",
} as const;
